using System.ComponentModel.DataAnnotations;
using Finstar.DatabaseMigrationGenerator.Application.Changeset;
using Finstar.DatabaseMigrationGenerator.Application.Metadata;
using Finstar.DatabaseMigrationGenerator.Application.Output;
using Finstar.DatabaseMigrationGenerator.Application.Structure;

namespace Finstar.DatabaseMigrationGenerator.Application.Migration;

public class MigrationService(
    IConsoleOutput console,
    IStructureValidationService structureValidationService,
    IMetadataGenerationService metadataGenerationService,
    IChangesetGenerationService changesetValidatorService) : IMigrationService
{
    public async Task CreateChangeSetsAsync(CreateChangeSetsCommand command)
    {
        var validationErrors = new List<string>();
        console.WriteLine();
        console.WriteSection("Structure Validation");
        try {
            structureValidationService.Validate(command.MigrationsPath);
        } catch (ValidationException ex) {
            validationErrors.Add(ex.Message);
        }

        console.WriteSection("Settings (YAML)");
        try {
            var metadata = await metadataGenerationService.Generate(command.MigrationsPath);
        } catch (ValidationException ex) {
            validationErrors.Add(ex.Message);
        }
        console.WriteLine();
        console.WriteSection("Changesets (SQL)");
        try {
            var changesets = await changesetValidatorService.ValidateAsync(command.MigrationsPath);
        } catch (ValidationException ex) {
            validationErrors.Add(ex.Message);
        }

        if (validationErrors.Count > 0) {
            console.WriteSection("Validation Summary");
            foreach (var error in validationErrors) {
                console.WriteError(error);
            }
            throw new ValidationException("Validation failed. See details above.");
        }

        //Generate changeset(metadata)
        

        //Map headers
        // var headerTable = headerTableReader.Get(settings.Table.HeaderTable);
        // yield return ConfigurationMapper.MapTable(settings.Table, headerTable?.Columns);




        //Read Migrationspath

        //Delete path DataBase/Migration/AutoGenerated/ChangeSetGenerator

        //Read all needed paths

        //Read all SettingsFiles
        //Validate all SettingsFiles.

        //other validations???

        //Search for specific file names like MdGroup.yaml -> if exists then create changeset
        // var mdGroups = _yamlDataRepository.ReadMdGroups();
        // var mdCacheLevels = _yamlDataRepository.ReadMdCacheLevels();
        // var mdDomainTypes = _yamlDataRepository.ReadMdDomainTypes();
        // var mdTableTypes = _yamlDataRepository.ReadMdTableTypes();
        // var mdVisumLevels = _yamlDataRepository.ReadMdVisumLevels();
        // var yamlData = new YamlDataModel(mdGroups, mdCacheLevels, mdDomainTypes, mdTableTypes, mdVisumLevels);



        // IOptions<LiquibaseSettings> liquibase,
        //     IOptions<SqlServerSettings> sql,
        // IOptions<MiscSettings> misc

        // Console.WriteLine($"Liquibase Settings: Run:{liquibase.Value.Run}");
        // Console.WriteLine($"Liquibase Settings: ExecutablePath:{liquibase.Value.ExecutablePath}");
        // Console.WriteLine($"Liquibase Settings: WorkingDirectory:{liquibase.Value.WorkingDirectory}");
        // Console.WriteLine($"Liquibase Settings: ContextFilter:{liquibase.Value.ContextFilter}");
        // Console.WriteLine($"Liquibase Settings: LabelFilter:{liquibase.Value.LabelFilter}");
        //
        // Console.WriteLine($"SqlServer Settings: HostName:{sql.Value.HostName}");
        // Console.WriteLine($"SqlServer Settings: InstanceName:{sql.Value.InstanceName}");
        // Console.WriteLine($"SqlServer Settings: DatabaseName:{sql.Value.DatabaseName}");
        // Console.WriteLine($"SqlServer Settings: Encrypt:{sql.Value.Encrypt}");
        // Console.WriteLine($"SqlServer Settings: TrustedServerCertificate:{sql.Value.TrustedServerCertificate}");
        // Console.WriteLine($"SqlServer Settings: IntegratedSecurity:{sql.Value.IntegratedSecurity}");
        //
        // Console.WriteLine($"Misc Settings: DoNotCreateTriggersForTables:{misc.Value.DoNotCreateTriggersForTables}");
        // Console.WriteLine($"Misc Settings: DoNotCreateGetDetailAndGetListForStoredProcedures:{misc.Value.DoNotCreateGetDetailAndGetListForStoredProcedures}");
    }
}