--liquibase formatted sql

--changeset system:create-alter-view-EvTransMessageChargeView context:any labels:c-any,o-view,ot-schema,on-EvTransMessageChargeView,fin-13659 runOnChange:true splitStatements:false stripComments:false endDelimiter:GO
--comment: Create view EvTransMessageChargeView
CREATE OR ALTER VIEW dbo.EvTransMessageChargeView AS
SELECT  TMC.Id,
	TMC.HdCreateDate,
	TMC.HdCreator,
	TMC.HdChangeDate,
	TMC.HdChangeUser,
	TMC.HdEditStamp,
	TMC.HdVersionNo,
	TMC.HdProcessId,
	TMC.HdStatusFlag,
	TMC.HdNoUpdateFlag,
	TMC.HdPendingChanges,
	TMC.HdPendingSubChanges,
	TMC.HdTriggerControl,
	TMC.TransMessageId,
	TMC.PositionId,
	TMC.TransChargeTypeId,
	TMC.ValueDate,
	TMC.RelatedToDebit,
	TMC.RelatedToDebitCv,
	TMC.IsDebitAmount,
	TMC.Currency,
	TMC.AmountChargeCurrency,
	TMC.RateToAcCu,
	TMC.Amount,
	TMC.AmountValue,
	TMC.BaseAmount,
	TMC.BaseAmountCurrency,
	TMC.ImmediateCharge,
	TMC.TextMasterId,
	TMC.Comment,
	TMC.CompletionDate,
	TMC.VatCode,
	TMX.RateBaCuHoCu,
	TMX.TaxAmountDa,
	TMX.TaxAmountDaHoCu,
	TMX.TaxAmountReclaim,
	TMX.TaxAmountReclaimHoCu,
	TMX.TaxRegulationCode,
	TMX.TaxEuCalcMethNo,
	TMX.CountryForEuTax,
	TMX.TaxRate,
	TMX.ReclaimInfoTextNo,
	TMX.ReclaimInfoRate,
	TMX.ReclaimInfoAmount,
	TMX.ReclaimInfoAmountHoCu,
	TMX.ReclaimAddTextNo,
	TMX.BaseQuantity, 
	TMX.BaseAmountHoCu, 
	TMX.TaxAmountPyCu
FROM	PtTransMessageCharge TMC
LEFT OUTER JOIN	PtTransMessageTax TMX ON TMC.Id = TMX.TransMessageChargeId  
