--liquibase formatted sql

--changeset system:create-alter-view-EvTransMessageView context:any labels:c-any,o-view,ot-schema,on-EvTransMessageView,fin-13659 runOnChange:true splitStatements:false stripComments:false endDelimiter:GO
--comment: Create view EvTransMessageView
CREATE OR ALTER VIEW dbo.EvTransMessageView AS
SELECT  PTM.Id,
	PTM.HdCreateDate,
	PTM.HdCreator,
	PTM.HdChangeDate,
	PTM.HdChangeUser,
	PTM.HdEditStamp,
	PTM.HdVersionNo,
	PTM.HdProcessId,
	PTM.HdStatusFlag,
	PTM.HdNoUpdateFlag,
	PTM.HdPendingChanges,
	PTM.HdPendingSubChanges,
	PTM.HdTriggerControl,
	PTM.TransactionId,
	PTM.PaymentCurrency,
	PTM.PaymentAmount,
	PTM.PaymentDate,
	PTM.TradeDate,
	PTM.TransMsgStatusNo,
	PTM.CancelTransMsgId,
	PTM.DebitGroupKey,
	PTM.DebitAdvice,
	PTM.DebitAccountNo,
	PTM.DebitPortfolioNo,
	PTM.DebitPortfolioId,
	PTM.DebitPrReferenceId,
	PTM.DebitAccountCurrency,
	PTM.DebitRateAcCuPfCu,
	PTM.DebitRate,
	PTM.DebitQuantity,
	PTM.DebitAmount,
	PTM.DebitCvCurrency,
	PTM.DebitAmountCv,
	PTM.DebitAmountCvAcCu,
	PTM.DebitCvAmountTypeNo,
	PTM.DebitValueDate,
	PTM.DebitTextNo,
	PTM.DebitLocGroupId,
	PTM.VatCode,
	PTM.CreditGroupKey,
	PTM.CreditAdvice,
	PTM.CreditAccountNo,
	PTM.CreditPortfolioNo,
	PTM.CreditPortfolioId,
	PTM.CreditPrReferenceId,
	PTM.CreditAccountCurrency,
	PTM.CreditRateAcCuPfCu,
	PTM.CreditCustomerReference,
	PTM.CreditRate,
	PTM.CreditQuantity,
	PTM.CreditAmount,
	PTM.CreditCvCurrency,
	PTM.CreditAmountCv,
	PTM.CreditAmountCvAcCu,
	PTM.CreditCvAmountTypeNo,
	PTM.CreditValueDate,
	PTM.CreditTextNo,
	PTM.CreditLocGroupId,
	PTM.ExternalPayeeId,
	PTM.TransText,
	PTM.MsgSequenceNumber, 
                TRA.TransNo, 
                TRA.TransTypeNo, 
                TRA.TransDate,
                PTM.IsTransitBooking
FROM      PtTransMessage PTM
JOIN        PtTransaction TRA ON TRA.Id = PTM.TransactionId
