--liquibase formatted sql

--changeset system:create-alter-view-PtAgrCardView04 context:any labels:c-any,o-view,ot-schema,on-PtAgrCardView04,fin-13659 runOnChange:true splitStatements:false stripComments:false endDelimiter:GO
--comment: Create view PtAgrCardView04
CREATE OR ALTER VIEW dbo.PtAgrCardView04 AS
SELECT  C.Id, 
                C.HdCreateDate, 
                C.HdCreator, 
                C.HdChangeDate, 
                C.HdChangeUser,
                C.HdEditStamp,
                C.HdVersionNo,
                C.HdProcessId, 
                C.HdStatusFlag,
                C.HdNoUpdateFlag,
                C.HdPendingChanges, 
                C.HdPendingSubChanges,
                C.HdTriggerControl,      
	C.CardId,
	B.CardNo,
	C.SerialNo,
	B.CardType,
	C.LineA,
	C.LineAFlagInd,
	C.LineB,
	C.LineBFlagInd,
	B.PartnerId,
	B.ContactPersonId,
	C.AddressTypeNo,
	C.AddressTypeNoFlagInd,
	B.AccountId,
	A.AccountNo,
	A.AccountNoEdited,
	A.TerminationDate,
	B.AuthorizationNo,
	C.OrderDate,
	C.IssueDate,
	C.ExpirationDate,
	C.ReturnDate,
	C.ServiceBancomat,
	C.ServiceBancomatFlagInd,
	C.ServicePos,
	C.ServicePosFlagInd,
	C.ServiceBank,
	C.ServiceBankFlagInd,
	C.ServiceCash,
	C.ServiceCashFlagInd,
	C.ServiceEMV,
	C.ServiceEMVFlagInd,
	C.LimitMonthTotal,
	C.LimitMonthTotalFlagInd,
	C.LimitMonthCash,
	C.LimitMonthCashFlagInd,
	C.LimitMonthOffline,
	C.LimitMonthOfflineFlagInd,
	C.LimitMonthOnline,
	C.LimitMonthOnlineFlagInd,
	C.LimitDayTotal,
	C.LimitDayTotalFlagInd,
	C.LimitDayCash,
	C.LimitDayCashFlagInd,
	C.LimitCashCard,
	C.LimitCashCardFlagInd,
	C.TransferPinCode,
	C.TransferPinCodeFlagInd,
	C.CashBoxLanguageNo,
	C.CashBoxLanguageNoFlagInd,
	C.ChipType,
	C.ChipTypeFlagInd,
	C.MailCode,
	C.MailCodeFlagInd,
	C.ExpressCode,
	C.ExpressCodeFlagInd,
	C.EMVProfileNo,
	C.EMVProfileNoFlagInd,
	C.EMVProfile,
	C.EMVProfileFlagInd,
	C.LockStatus,
	C.LockDate,
	C.CardStatus,
	C.TransactionType,
	PB.CardNo As CardNoPrevious,
	PC.SerialNo As SerialNoPrevious,
	PC.OrderDate As OrderDatePrevious,
	PC.IssueDate As IssueDatePrevious,
	PC.ExpirationDate As ExpirationDatePrevious,
	PC.ReturnDate As ReturnDatePrevious,
                PTB.BranchNo,
                C.CardHolderDestFlag,
                C.AgentId
FROM PtAgrCard As C
INNER JOIN PtAgrCardBase As B ON C.CardId = B.Id
LEFT OUTER JOIN PtAccountBase As A ON B.AccountId = A.Id
LEFT OUTER JOIN PtPortfolio As P ON A.PortfolioId = P.Id
INNER JOIN PtBase As PTB ON B.PartnerId = PTB.Id
LEFT OUTER JOIN PtAgrCard As PC ON (C.IdPrevious = PC.Id)
LEFT OUTER JOIN PtAgrCardBase As PB ON (PC.CardId = PB.Id)
WHERE C.CardStatus < 50
