--liquibase formatted sql

--changeset system:create-alter-view-TransToBeReportedInitialView context:any labels:c-any,o-view,ot-schema,on-TransToBeReportedInitialView,fin-13659 runOnChange:true splitStatements:false stripComments:false endDelimiter:GO
--comment: Create view TransToBeReportedInitialView
CREATE OR ALTER VIEW dbo.TransToBeReportedInitialView AS
SELECT  STV.BROKERPORTFOLIOID  
, STV.PTTRANSTRADEID      
, POD.PORTFOLIONO        
, TOM.ISSTOCKEXORDER     
, TOM.TRADINGORDERID     
, PTTRANSACTION.TRANSNO  
, ISNULL(UPPER(PTO.BANKSHORTNAMEPARTNER),'') + REPLACE(PTTR.ID, '-', '') AS TXREPORTID  
, CASE WHEN STV.TRANSMSGSTATUSNO = 2 THEN '4' ELSE '0' END    AS TXREPORTTRANSTYPE        
, ISNULL(UPPER(PTO.BANKSHORTNAMEPARTNER),'') + REPLACE(PTTR.ID, '-', '') AS TXGROUPID        
, 1 AS INSTRUMENTTYPE    
, isnull(PTTR.StockExRef,'') AS TRDMATCHID  
, PDV.ISINNO AS ISIN     
, '' AS CFICODE        
, '' AS UNDERLYINGISIN  
, '' AS UNDERLYINGISIN2       
, '' AS UNDERLYINGISIN3       
, CONVERT(INT, STV.TRADEQUANTITY) AS LASTQTY  
, CONVERT(DECIMAL(10,2)
, ROUND(STV.TRADEPRICE * 20, 0) / 20) AS LASTPX   
, CASE WHEN PRPUBLIC.UNITNO IN (1) THEN '1' ELSE '2' END AS PRICETYPE       
, FORMAT(stv.TradeDate , 'yyyyMMdd-HH:mm:ss.mmm' + '0000') AS EXECUTIONTIME 
,CONVERT(CHAR(8),STV.PAYMENTDATE, 112) AS SETTLDATE  
, CASE WHEN PTT.TRANSTYPENO IN (54, 601, 621) THEN '1' ELSE '2' END AS ENTERINGFIRMSIDE        
, '' AS ENTERINGFIRMSECONDARYCLORDID        
, 'X' AS ENTERINGFIRMORDERCAPACITY   
, 'XXXX' AS ENTERINGFIRMPARTYID    
, 'XXXXXXXXXXXXXXXXX' AS ENTERINGFIRMPERSON  
,CONTRAFIRMSUBTYPE = CAST(null as nvarchar(4))  
,CONTRAFIRMPARTYID = CAST(null as nvarchar(35)) 
, CASE  WHEN TOM.BENEFICIALOWNER IS NULL THEN 'I'        
       WHEN  SUBSTRING(TOM.BENEFICIALOWNER, 12, 1) = '-' THEN 'N'  
       WHEN SUBSTRING(TOM.BENEFICIALOWNER, 12, 1) <> '-' THEN 'J'  
END AS BENEFICIALOWNERTYPE  
, ISNULL(TOM.BENEFICIALOWNER, '') AS BENEFICIALOWNER  
, ISNULL(TOM.BENEFICIALOWNERDESCRIPTION, '')      AS BENEFICIALOWNERDESCRIPTION  
, PTM.PAYMENTCURRENCY AS CURRENCY      
, '' AS CHFAMOUNT      
, '' AS UNDERLYINGSYMBOL      
, '' AS EXPIRATIONYEAR        
, '' AS EXPIRATIONMONTH              
, '' AS SERIESCLASSCODE              
, '' AS EXERCISEPRICE                
, '' AS SERIESVERSIONNUMBER   
, '' AS LEVERAGEINDICATOR            
FROM    PTSECURITYTRADESVIEWFORSIX STV                
LEFT OUTER JOIN PTPORTFOLIO POD ON POD.ID = STV.BROKERPORTFOLIOID   
LEFT OUTER JOIN PTTRANSTYPE PTT ON PTT.ID = STV.TRANSTYPEID         
INNER JOIN PRPUBLICDESCRIPTIONVIEW PDV ON PDV.ID = STV.PUBLICID AND PDV.LANGUAGENO = 2       
INNER JOIN PRPUBLIC ON PRPUBLIC.ID = PDV.ID AND PrPublic.InstrumentTypeNo <> 4                 
INNER JOIN PTTRANSMESSAGE PTM ON PTM.ID = STV.TRADEMESSAGEID AND PTM.HDVERSIONNO BETWEEN 1 AND 999999998     
INNER JOIN PTTRADINGORDERMESSAGE TOM ON PTM.ID = TOM.TRANSMESSAGEID AND TOM.HDVERSIONNO < 999999999 AND TOM.BENEFICIALOWNER IS NOT NULL       
LEFT OUTER JOIN PTTRANSTRADE PTTR ON PTTR.ID = STV.PTTRANSTRADEID AND PTTR.HDVERSIONNO < 999999999       
INNER JOIN PTTRANSACTION ON PTTRANSACTION.ID = PTM.TRANSACTIONID AND PTTRANSACTION.HDVERSIONNO BETWEEN 1 AND 999999998       
JOIN PRPUBLICSIXREPORTING PPUSR ON PPUSR.PUBLICID = PRPUBLIC.ID AND PPUSR.DATEFROM <= STV.TRADEDATE AND PPUSR.DATETO >= STV.TRADEDATE AND PPUSR.HASTOBEREPORTED = 1      
JOIN PTTRADINGORDER PTO ON TOM.TRADINGORDERID = PTO.ID  
WHERE 1 = 0 

