--liquibase formatted sql

--changeset system:create-alter-view-PtTransStockExView context:any labels:c-any,o-view,ot-schema,on-PtTransStockExView,fin-13659 runOnChange:true splitStatements:false stripComments:false endDelimiter:GO
--comment: Create view PtTransStockExView
CREATE OR ALTER VIEW dbo.PtTransStockExView AS
SELECT top 500
     M.Id, 
     M.HdCreateDate,
     M.HdCreator,
     M.HdChangeDate,
     M.HdChangeUser,
     M.HdEditStamp,
     M.HdVersionNo,
     M.HdProcessId,
     M.HdStatusFlag,
     M.HdNoUpdateFlag,
     M.HdPendingChanges,
     M.HdPendingSubChanges,
     M.HdTriggerControl,
     M.TransMsgStatusNo,
     M.CancelTradOrderMsgId,
     CAST(null as uniqueidentifier) as TradingSystemGroupId,
     CAST(null as uniqueidentifier) as TradingSystemId,
     T.IsAlreadyTraded,
     T.IsKeepingInterest,
     T.IsKeepingInterest as IsAutoOrderRouting,
     PtTransSxOrderStatus.OrderStatusNo,
     M.PublicTradingPlaceId,
     M.IsOffExchange,
     M.PaymentCurrency,
     M.PaymentDate,
     M.OrderQuantity,
     IsNull(M.OrderQuantity,0) as MarketValue,
     M.TransSxRebateNo,
     M.TextForRebate, 
     M.IsStockExOrder, 
     M.AccountRate,
     M.SettlementRate,
     CAST (null as float) as AccountRateBroker,
     CAST (null as float)  as SettlementRateBroker,
     CAST(null as uniqueidentifier) as SecurityPortfolioIdBroker,
     CAST(null as uniqueidentifier)  as SecurityPrReferenceIdBroker,
     CAST(null as uniqueidentifier)  as AccountPortfolioIdBroker,
     CAST(null as uniqueidentifier)  as AccountPrReferenceIdBroker,
     CAST(null as uniqueidentifier)  as AccountPrReferenceIdBroFutures,
     M.LocGroupId LocGroupIdBroker,
     CAST(null as uniqueidentifier) as SecurityPortfolioId,
     CAST(null as uniqueidentifier) as SecurityPrReferenceId,
     M.LocGroupId,
     M.AccountPortfolioId,
     M.AccountPrReferenceId,
     CAST(null as uniqueidentifier)  as AccountPrReferenceIdFutures,
     CAST(null as integer) as CvAmountTypeNo,
     T.Id TradingOrderId,
     T.TransNo,
     T.TransNoOrig,
     T.OrderNo,
     T.OrderDate,
     T.OrderMediaNo,
     T.TransTypeNo,
     T.PublicId,
     T.ExtUnknownIsinNo,
     T.ExtUnknownIsinNoStatus,
     T.IsInstrumentFastOpening, 
     CAST(null as varchar(40)) as PrPublicShortName,
     P.UsIrsIncomeCode,
     P.SmallDenom, 
     P.IssuerId,
     T.IsKeepingInterest as IsMaturityDate, 
     M.MaturityDate,
     M.InterestRate,
     T.IsKeepingInterest as IsShortToff,
     T.IsKeepingInterest as IsOwnBond,
     CAST(null as integer) as TitleNo,
     CAST(null as varchar) as SpecialKey,
     CAST(null as uniqueidentifier) as ObligationId,
     CAST(null as uniqueidentifier) as InsurancePoliceId,
     CAST(null as uniqueidentifier) as ObjectId,
     T.PreferredPublicListingId,
     T.OrderTypeNo,
     T.PriceLimit,
     T.TriggerPrice,
     T.ValidFrom,
     T.ValidToRule,
     T.ValidTo,
     T.TextToTrader,
     T.TextToPartner,
     T.TextToBackOffice,
     T.TextToForexTrader,
     T.OrderDisposerId,
     T.OrderMiddlemanId,
     T.AllocationStatus,
     T.PlaceStatus,
     PtTransType.SecurityBookingSide,
     PtTransOrderMedia.IsSxOrderAuthValueSpecial,
     T.IsKeepingInterest as IsEBankingWithBlocking,
     T.IsKeepingInterest as IsRestrictionWarning,
     T.IsKeepingInterest as IsOtherWarning,
     T.IsKeepingInterest as IsFondsSaving,
     T.IsKeepingInterest as IsFondsBuyWithConsulting,
     M.BankInternalReference as BankInternalReferencePartner, 
     CAST(null as varchar) as BankShortNamePartner,
     M.BankInternalReference as BankInternalReferenceTrader,
     T.IsKeepingInterest as IsFondsToNAV,
     PtTransSxOrderAdvisory.OrderAdvisoryNo,  T.IsKeepingInterest as IsGenerateContactReport,
	 CAST(null as uniqueidentifier) as ContactReportId,
     M.GoiApp,
     M.GoiChannel,
     T.IsKeepingInterest as IsBlockingWarning,
     CAST(null as varchar(4000)) as WarningInfo,
     CAST(null as varchar(50)) as ExtOrderCreator,
     CAST(null as varchar(100)) as ExtOrderMandator,
     T.IsKeepingInterest as IsNotBestExecution,
     T.IsKeepingInterest as IsWithESGWarning, 
     T.IsKeepingInterest as IsOrderByNAVAmount, 
     M.OrderNAVAmount 
     FROM
     PtTradingOrderMessage M
     JOIN PtTradingOrder T ON T.Id = M.TradingOrderId
     JOIN PtTransType ON PtTransType.TransTypeNo = T.TransTypeNo
     AND (PtTransType.SecurityBookingSide = 'C' or SecurityBookingSide = 'D')
     AND PtTransType.HdVersionNo between 1 and 999999998
     JOIN PrPublic P ON P.Id = T.PublicId
     AND P.HdVersionNo between 1 and 999999998
     JOIN PtTransOrderMedia ON PtTransOrderMedia.OrderMediaNo = T.OrderMediaNo
     AND PtTransOrderMedia.HdVersionNo between 1 and 999999998
     JOIN PtTransSxOrderStatus ON PtTransSxOrderStatus.OrderStatusNo = M.OrderStatusNo
     AND PtTransSxOrderStatus .HdVersionNo between 1 and 999999998
     JOIN PtTransSxOrderAdvisory ON PtTransSxOrderAdvisory.OrderAdvisoryNo = M.OrderAdvisoryNo
     AND PtTransSxOrderAdvisory.HdVersionNo between 1 and 999999998
