--liquibase formatted sql

--changeset system:create-alter-view-PtPositionSecuritiesVaLastView context:any labels:c-any,o-view,ot-schema,on-PtPositionSecuritiesVaLastView,fin-13659 runOnChange:true splitStatements:false stripComments:false endDelimiter:GO
--comment: Create view PtPositionSecuritiesVaLastView
CREATE OR ALTER VIEW dbo.PtPositionSecuritiesVaLastView AS
SELECT 
V.ID AS Id,
V.HdCreateDate, 
V.HdCreator, 
V.HdChangeDate, 
V.HdEditStamp, 
V.HdVersionNo, 
V.HdProcessId, 
V.HdStatusFlag, 
V.HdNoUpdateFlag, 
V.HdPendingChanges, 
V.HdPendingSubChanges, 
V.HdTriggerControl, 
V.PortfolioID AS PortfolioId,
V.Quantity,
V.ProdLocGroupID AS ProdLocGroupId,
V.PortfolioName,
V.Description,
V.ProdReferenceID AS ProdReferenceId,
V.PositionCurrency,
V.ReferenceData, 
V.PublicID AS PublicId,
V.PublicDescription, 
V.ShortName, 
V.LongName, 
V.InstrumentTypeNo,
V.NominalCurrency,
V.ISINNo AS IsinNo,
V.VDFInstrumentSymbol,
V.UnitNo,
V.SecurityType, 
V.IssuerId, 
V.LanguageNo,
V.HasPendingOrder,
V.IsToClose,
V.ObjectObjectSeqNo,
V.ObligationObjectSeqNo,
V.InsuranceObjectSeqNo,
V.ObjectId,
V.ObligationId,
V.InsuranceId,
V.ObjectDescription,
P.VaRunId,
P.ValuationDate,
P.PublicPriceId,
P.PriceDate,
P.PriceCurrency,
P.ValuationCurrency,
P.Rate, 
P.RatePrCuVaCu,
P.RatePrCuCHF,
P.RatePrCurAcCur, 
P.MarketValueVaCu, 
P.MarketValueCHF, 
P.AccruedInterestVaCu, 
P.AccruedInterestCHF, 
P.CollateralRate, 
P.CollateralValueVaCu,
P.CollateralValueCHF,
TP.Name as PublicTradingPlaceName,
PP.PriceQuoteType
FROM PtPositionSecuritiesView V
LEFT OUTER JOIN VaLatestRunRef R ON R.PortfolioId = V.PortfolioID
LEFT OUTER JOIN VaLatestValuationForPosition P ON P.PortfolioId = R.PortfolioId AND P.VaRunId = R.VaRunId AND P.PositionId = V.Id
LEFT OUTER JOIN PrPublicPrice PP on PP.ID = P.PublicPriceId 
LEFT OUTER JOIN PrPublicTradingPlace TP on TP.ID = PP.PublicTradingPlaceId
