--liquibase formatted sql

--changeset system:create-alter-procedure-DbJobControlUpdate context:any labels:c-any,o-stored-procedure,ot-schema,on-DbJobControlUpdate,fin-13659 runOnChange:true splitStatements:false stripComments:false endDelimiter:GO
--comment: Create stored procedure DbJobControlUpdate
CREATE OR ALTER PROCEDURE dbo.DbJobControlUpdate
@SEQ_ID					BIGINT,
	@JOB_SEQ_KEY		INT				= 1,
	@JOB_CODE			VARCHAR(4),
	@JOB_DATE			VARCHAR(10),
	@EXE_ACTUAL_START	VARCHAR(25)		= '',
	@EXE_ACTUAL_END		VARCHAR(25)		= '',
	@FOR_DATETIME_FROM	VARCHAR(25)		= '',
	@FOR_DATETIME_TO	VARCHAR(25)		= '',
	@STATUS				INT				= 0,
	@JOB_REC_COUNT1		INT				= 0,
	@JOB_REC_COUNT2		INT				= 0,
	@OBJECT_NAME		VARCHAR(50)		= '',
	@DETAIL				VARCHAR(4000)	= '-',
	@FLAG				VARCHAR(1)		= 'M',
	@RECORD_REF_ID		BIGINT			= 0 OUTPUT,
	@RECORD_REF_GUID 	UNIQUEIDENTIFIER = 0x0	OUTPUT
	AS
	
	DECLARE @CHANGERESULT TABLE (CHANGETYPE VARCHAR(10), RECORD_REF_ID INTEGER, RECORD_REF_GUID uniqueidentifier)
	
	BEGIN
	
		IF(@FLAG = 'M')
			BEGIN
				MERGE INTO AsExternalAppTransferProcess TARGET
		          USING (SELECT @SEQ_ID SEQID, 
							@JOB_SEQ_KEY JOB_SEQ_KEY,
							@JOB_CODE JOB_CODE, 
							@JOB_DATE JOB_DATE, 
							@EXE_ACTUAL_START EXE_ACTUAL_START,
							@EXE_ACTUAL_END EXE_ACTUAL_END,
							@FOR_DATETIME_FROM FOR_DATETIME_FROM,
							@FOR_DATETIME_TO FOR_DATETIME_TO,
							@STATUS STATUS,
							@JOB_REC_COUNT1 JOB_REC_COUNT1,
							@JOB_REC_COUNT2 JOB_REC_COUNT2) 
						AS SOURCE 
							(SEQID, JOB_SEQ_KEY, JOB_CODE, JOB_DATE, EXE_ACTUAL_START, EXE_ACTUAL_END,
									FOR_DATETIME_FROM, FOR_DATETIME_TO, STATUS, JOB_REC_COUNT1, JOB_REC_COUNT2)
		             ON (TARGET.JobSeqKey = SOURCE.JOB_SEQ_KEY AND TARGET.JobCode = SOURCE.JOB_CODE AND TARGET.JobDate = SOURCE.JOB_DATE AND TARGET.STATUS = 9 )
					 --ON (TARGET.ID = SOURCE.ID )
					WHEN MATCHED THEN 
						UPDATE SET 
							TARGET.ExeActualEnd = SOURCE.EXE_ACTUAL_END,
							TARGET.STATUS = SOURCE.STATUS,
							TARGET.JobRecCount1 = SOURCE.JOB_REC_COUNT1,
							TARGET.JobReccount2 = SOURCE.JOB_REC_COUNT2
		
					WHEN NOT MATCHED BY TARGET THEN 
						INSERT (JobSeqKey, JobCode, JOBDATE, EXEACTUALSTART, EXEACTUALEND,
									FORDATETIMEFROM, FORDATETIMETO, STATUS, JOBRECCOUNT1, JOBRECCOUNT2)
		                         VALUES (SOURCE.JOB_SEQ_KEY, SOURCE.JOB_CODE, SOURCE.JOB_DATE, SOURCE.EXE_ACTUAL_START, SOURCE.EXE_ACTUAL_END,
										SOURCE.FOR_DATETIME_FROM, SOURCE.FOR_DATETIME_TO, SOURCE.STATUS, SOURCE.JOB_REC_COUNT1, SOURCE.JOB_REC_COUNT1)
					OUTPUT $ACTION, ISNULL(INSERTED.SEQID, @SEQ_ID), INSERTED.ID INTO @CHANGERESULT;
					
					SELECT @RECORD_REF_ID = MAX(RECORD_REF_ID), @RECORD_REF_GUID =  RECORD_REF_GUID FROM @CHANGERESULT GROUP BY RECORD_REF_GUID;
					 
			END
		ELSE
		IF(@FLAG = 'D')
			BEGIN
				MERGE INTO AsExtAppTransferProcessDetail TARGET
		          USING (SELECT @SEQ_ID JOB_CONTROL_ID, 
							@JOB_SEQ_KEY JOB_SEQ_KEY,
							@JOB_CODE JOB_CODE, 
							@JOB_DATE JOB_DATE, 
							@EXE_ACTUAL_START EXE_ACTUAL_START,
							@EXE_ACTUAL_END EXE_ACTUAL_END,
							@OBJECT_NAME OBJECT_NAME,
							@STATUS STATUS,
							@JOB_REC_COUNT1 JOB_REC_COUNT1,
							@JOB_REC_COUNT2 JOB_REC_COUNT2,
							@DETAIL DETAIL) 
						AS SOURCE 
							(JOB_CONTROL_ID, JOB_SEQ_KEY, JOB_CODE, JOB_DATE, EXE_ACTUAL_START, EXE_ACTUAL_END,
									OBJECT_NAME, STATUS, JOB_REC_COUNT1, JOB_REC_COUNT2, DETAIL)
		             --ON (TARGET.ID = SOURCE.ID AND TARGET.JOB_CODE = SOURCE.JOB_CODE AND TARGET.JOB_DATE = SOURCE.JOB_DATE)
					 ON (TARGET.ExternAppTransferProcessSeqId  = SOURCE.JOB_CONTROL_ID AND TARGET.JOBCODE = SOURCE.JOB_CODE AND TARGET.JOBDATE = SOURCE.JOB_DATE AND TARGET.OBJECTNAME = SOURCE.OBJECT_NAME)
					WHEN MATCHED THEN 
						UPDATE SET 
							--TARGET.EXE_ACTUAL_START = SOURCE.EXE_ACTUAL_START,
							TARGET.EXEACTUALEND = SOURCE.EXE_ACTUAL_END,
							TARGET.STATUS = SOURCE.STATUS,
							TARGET.JOBCOUNT1 = SOURCE.JOB_REC_COUNT1,
							TARGET.JOBCOUNT2 = SOURCE.JOB_REC_COUNT2,
							TARGET.DETAIL = SOURCE.DETAIL
		
					WHEN NOT MATCHED BY TARGET THEN 
						INSERT (ExternAppTransferProcessSeqId , JOBCODE, JOBDATE, EXEACTUALSTART, EXEACTUALEND,
									OBJECTNAME, STATUS, JOBCOUNT1, JOBCOUNT2, DETAIL)
		                VALUES (SOURCE.JOB_CONTROL_ID, SOURCE.JOB_CODE, SOURCE.JOB_DATE, SOURCE.EXE_ACTUAL_START, SOURCE.EXE_ACTUAL_END,
									SOURCE.OBJECT_NAME, SOURCE.STATUS, SOURCE.JOB_REC_COUNT1, SOURCE.JOB_REC_COUNT2, SOURCE.DETAIL);
									
					--OUTPUT $ACTION, ISNULL(INSERTED.JOB_CONTROL_ID, @ID) INTO @CHANGERESULT;
				
				--SELECT @RECORD_REF_ID = MAX(ID) FROM @CHANGERESULT; 
				SET @RECORD_REF_ID = @SEQ_ID; 
			END
  END;   
