--liquibase formatted sql

--changeset system:create-alter-view-VaPositionView context:any labels:c-any,o-view,ot-schema,on-VaPositionView,fin-13659 runOnChange:true splitStatements:false stripComments:false endDelimiter:GO
--comment: Create view VaPositionView
CREATE OR ALTER VIEW dbo.VaPositionView AS
--View: VaPositionView

SELECT [VaRunId]
      ,[PartnerId]
      ,[PortfolioId]
      ,[PositionId]
      ,[ProdReferenceId]
      ,[PublicPriceId]
      ,[PriceDate]
      ,[PortfolioNo]
      ,[ValuationCurrency]
      ,[PriceCurrency]
      ,[Quantity]
      ,[Rate]
      ,[RatePrCuVaCu]
      ,[RatePrCuCHF]
      ,[RatePrCurAcCur]
      ,[MarketValuePrCu]
      ,[AccruedInterestPrCu]
      ,[MarketValueVaCu]
      ,[AccruedInterestVaCu]
      ,[MarketValueCHF]
      ,[AccruedInterestCHF]
      ,[Delay]
      ,[CollateralRate]
      ,[NotActual]
      ,[PriceQuoteType]
      ,[NoReporting] 
      , cast(0 as bit) As [IsAccountPos]
  FROM [VaPublicView]

UNION

SELECT [VaRunId]
      ,[PartnerId]
      ,[PortfolioId]
      ,[PositionId]
      ,[ProdReferenceId]
      ,[PublicPriceId]
      ,[PriceDate]
      ,[PortfolioNo]
      ,[ValuationCurrency]
      ,[PriceCurrency]
      ,[Quantity]
      ,[Rate]
      ,[RatePrCuVaCu]
      ,[RatePrCuCHF]
      ,[RatePrCuVaCu] as [RatePrCurAcCur]
      ,[MarketValuePrCu]
      ,[AccruedInterestPrCu]
      ,[MarketValueVaCu]
      ,[AccruedInterestVaCu]
      ,[MarketValueCHF]
      ,[AccruedInterestCHF]
      ,[Delay]
      ,[CollateralRate]
      ,[NotActual]
      ,[PriceQuoteType]
      ,[NoReporting] 
      , cast(1 as bit) As [IsAccountPos]
  FROM [VaPrivateView]

