--liquibase formatted sql

--changeset system:create-alter-function-DbJobAreDependentDone context:any labels:c-any,o-function,ot-schema,on-DbJobAreDependentDone,fin-13659 runOnChange:true splitStatements:false stripComments:false endDelimiter:GO
--comment: Create function DbJobAreDependentDone
CREATE OR ALTER FUNCTION dbo.DbJobAreDependentDone
 (@JOB_CODE  VARCHAR(4), @JOB_DATE VARCHAR(10), @PREV_DAY_DATE VARCHAR(10) = '') 
RETURNS INT
  AS
    
  BEGIN
	DECLARE @RET  INT;
	--DECLARE @PREV_DAY_DATE VARCHAR(10)


	DECLARE	@DEPENDENT_JOB_CODE1	VARCHAR(4)
	DECLARE	@DEPENDENT_JOB_CODE2	VARCHAR(4)
	DECLARE	@SUCCESSOR_JOB_CODE1	VARCHAR(4)
	DECLARE	@SUCCESSOR_JOB_CODE2	VARCHAR(4)
	
	IF (@PREV_DAY_DATE IS NULL OR @PREV_DAY_DATE = '')
		SET @PREV_DAY_DATE = CONVERT(VARCHAR(10),DATEADD(DD, -1, @JOB_DATE),112)
		
	SET @RET = 1 -- NO DEPENDENCY
	SELECT 
			@DEPENDENT_JOB_CODE1 = LEFT(CONCAT(ISNULL(DependentJobCode1,'0000'), '0000'),4) ,
			@DEPENDENT_JOB_CODE2 = LEFT(CONCAT(ISNULL(DependentJobCode2,'0000'), '0000'),4) ,
			@SUCCESSOR_JOB_CODE1 = LEFT(CONCAT(ISNULL(SuccessorJobCode1,'0000'), '0000'),4) ,
			@SUCCESSOR_JOB_CODE2 = LEFT(CONCAT(ISNULL(SuccessorJobCode2,'0000'), '0000'),4) 
			FROM DbJob
			WHERE JobCode = @JOB_CODE

	IF(@DEPENDENT_JOB_CODE1 = '0000' OR @DEPENDENT_JOB_CODE1 IS NULL)
		SET @RET = 1	-- NO DEPENDENT1 JOB
	ELSE
	BEGIN
		SELECT @RET = dbo.DbJobisDone(@DEPENDENT_JOB_CODE1, @JOB_DATE)
			IF (@RET IS NULL OR @RET < 1)
				RETURN 0	-- DEPENDENT1 JOB DOES NOT COMPLETED
			ELSE
				SET @RET = 1	-- DEPENDENT1 JOB COMPLETED
	END

	IF((@DEPENDENT_JOB_CODE2 = '0000' OR @DEPENDENT_JOB_CODE2 IS NULL) AND @RET = 1)
		SET @RET = 1	-- NO DEPENDENT2 JOB
	ELSE
	BEGIN
		SELECT @RET = dbo.DbJobisDone(@DEPENDENT_JOB_CODE2, @JOB_DATE)
			IF (@RET IS NULL OR @RET < 1)
				RETURN 0 -- DEPENDENT1 JOB DOES NOT COMPLETED
			ELSE
				SET @RET = 1	-- DEPENDENT1 JOB COMPLETED
	END

	IF((@SUCCESSOR_JOB_CODE1 = '0000' OR @SUCCESSOR_JOB_CODE1 IS NULL) AND @RET = 1)
		SET @RET = 1	-- NO SUCCESSOR1 JOB
	ELSE
	BEGIN
		SELECT @RET = dbo.DbJobisDone(@SUCCESSOR_JOB_CODE1, @PREV_DAY_DATE)
			IF (@RET IS NULL OR @RET < 1)
				RETURN 0 -- SUCCESSOR1 JOB DOES NOT COMPLETED
			ELSE
				SET @RET = 1	-- SUCCESSOR1 JOB IS COMPLETED, PROCEED
	END

	IF((@SUCCESSOR_JOB_CODE2 = '0000' OR @SUCCESSOR_JOB_CODE2 IS NULL) AND @RET = 1)
		SET @RET = 1	-- NO SUCCESSOR2 JOB
	ELSE
	BEGIN
		SELECT @RET = dbo.DbJobisDone(@SUCCESSOR_JOB_CODE2, @PREV_DAY_DATE)
			IF (@RET IS NULL OR @RET < 1)
				RETURN 0 -- SUCCESSOR2 JOB DOES NOT COMPLETED
			ELSE
				SET @RET = 1	-- SUCCESSOR2 JOB IS COMPLETED, PROCEED
	END

	RETURN @RET	

   END;
