--liquibase formatted sql

--changeset system:create-alter-view-CoEinzelWbDiffView context:any labels:c-any,o-view,ot-schema,on-CoEinzelWbDiffView,fin-13659 runOnChange:true splitStatements:false stripComments:false endDelimiter:GO
--comment: Create view CoEinzelWbDiffView
CREATE OR ALTER VIEW dbo.CoEinzelWbDiffView AS
select   
akt.collno ,
akt.wbdescription ,
akt.actflag ,
akt.dayendflag ,
akt.monthendflag ,
akt.quartendflag ,
akt.mevyear ,
akt.mevmonth ,
akt.ownerid ,
akt.ptdescription ,
akt.accountnoedited ,
akt.veragrp ,   
akt.veradate ,   
akt.veradateshort ,   
akt.limit ,   
akt.debitbalance ,   
akt.deckungswertohnewb ,   
akt.currency ,   
akt.limitkw ,   
akt.debitbalancekw ,   
akt.exflag ,   
akt.wbassigned ,   
akt.productid ,   
akt.producttext ,   
akt.collateralid ,   
akt.accountid ,   
akt.coveradetid ,   
akt.allowanceamount ,   
akt.accrualsamount ,   
akt.riskamount , 
          (select top 1 prev.allowanceamount from CoEinZelWbView as prev where prev.wbassigned = 1 and prev.accountid = akt.accountid and            prev.veragrp < akt.veragrp order by prev.veragrp desc) as prevallowanceamount,
          (select top 1 prev.accrualsamount from CoEinZelWbView as prev where prev.wbassigned = 1 and prev.accountid = akt.accountid and               prev.veragrp < akt.veragrp order by prev.veragrp desc) as prevaccrualsamount,
          (select top 1 prev.riskamount from CoEinZelWbView as prev where prev.wbassigned = 1 and prev.accountid = akt.accountid and            prev.veragrp < akt.veragrp order by prev.veragrp desc) as prevriskamount,
          akt.allowanceamount - isnull((select top 1 prev.allowanceamount from CoEinZelWbView as prev where prev.wbassigned = 1 and                      prev.accountid = akt.accountid and prev.veragrp < akt.veragrp order by prev.veragrp desc),0) as diffallowanceamount,
           akt.accrualsamount - isnull((select top 1 prev.accrualsamount from CoEinZelWbView as prev where prev.wbassigned = 1 and                       prev.accountid = akt.accountid and prev.veragrp < akt.veragrp order by prev.veragrp desc),0) as diffaccrualsamount,
           akt.riskamount - isnull((select top 1 prev.riskamount from CoEinZelWbView as prev where prev.wbassigned = 1 and prev.accountid =                 akt.accountid and prev.veragrp < akt.veragrp order by prev.veragrp desc),0) as diffriskamount,
           (select top 1 prev.veragrp from CoEinZelWbView as prev where prev.wbassigned = 1 and prev.accountid = akt.accountid and                       prev.veragrp < akt.veragrp order by prev.veragrp desc) as prevveragrp,
           (select top 1 prev.veradate from CoEinZelWbView as prev where prev.wbassigned = 1 and prev.accountid = akt.accountid and                       prev.veragrp < akt.veragrp order by prev.veragrp desc) as prevveradate,
           (select top 1 prev.coveradetid from CoEinZelWbView as prev where prev.wbassigned = 1 and prev.accountid = akt.accountid and                    prev.veragrp < akt.veragrp order by prev.veragrp desc) as prevcoveradetid
from CoEinZelWbView as akt  where  akt.wbassigned = 1
