// -----------------------------------------------------------------------------
// <copyright company="Hypothekarbank Lenzburg">
//     Copyright (c) Hypothekarbank Lenzburg. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace Finstar.DatabaseMigrationGenerator.Application.Structure
{
    public partial class StructureValidationService : IStructureValidationService
    {
        private readonly List<string> _errors = [];

        [GeneratedRegex(@"^[A-Z][a-z]$", RegexOptions.Compiled)]
        private static partial Regex TwoCharFolderPattern();

        public void Validate(string migrationsPath)
        {
            _errors.Clear();

            Console.Write("Validating structure...");

            ValidateRootFolder(migrationsPath);
            ValidateAutoGenerated(migrationsPath);
            ValidateFunctions(migrationsPath);
            ValidateViews(migrationsPath);
            ValidateStoredProcedures(migrationsPath);
            ValidateTables(migrationsPath);

            if (_errors.Count > 0) {
                Console.WriteLine();
                Console.WriteLine();
                Console.WriteLine("Structure validation errors found:");
                Console.WriteLine();
                foreach (var error in _errors) {
                    Console.ForegroundColor = ConsoleColor.DarkRed;
                    Console.WriteLine($"    - {error}");
                    Console.ResetColor();
                }
                Console.WriteLine();
                throw new ValidationException($"Structure validation failed with {_errors.Count} error(s).");
            }

            Console.WriteLine(" done");
            Console.ForegroundColor = ConsoleColor.DarkGreen;
            Console.WriteLine("Folder structure validated successfully!");
            Console.ResetColor();
        }

        private void ValidateRootFolder(string path)
        {
            ValidateAllowedFiles(path, StructureRules.RootAllowedFiles, "Migrations/");
            ValidateAllowedFolders(path, StructureRules.RootAllowedFolders, "Migrations/");
        }

        private void ValidateAutoGenerated(string migrationsPath)
        {
            var path = Path.Combine(migrationsPath, "AutoGenerated");
            if (!Directory.Exists(path)) return;

            ValidateNoFiles(path, "Migrations/AutoGenerated/");
            ValidateAllowedFolders(path, StructureRules.AutoGeneratedAllowedFolders, "Migrations/AutoGenerated/");

            // Baseline
            var baselinePath = Path.Combine(path, "Baseline");
            if (Directory.Exists(baselinePath)) {
                ValidateExactFiles(baselinePath, StructureRules.BaselineAllowedFiles, "Migrations/AutoGenerated/Baseline/");
                ValidateNoFolders(baselinePath, "Migrations/AutoGenerated/Baseline/");
            }

            // ChangesetGenerator
            var changesetPath = Path.Combine(path, "ChangesetGenerator");
            if (Directory.Exists(changesetPath)) {
                ValidateExactFiles(changesetPath, StructureRules.ChangesetGeneratorAllowedFiles, "Migrations/AutoGenerated/ChangesetGenerator/");
                ValidateNoFolders(changesetPath, "Migrations/AutoGenerated/ChangesetGenerator/");
            }
        }

        private void ValidateFunctions(string migrationsPath)
        {
            var path = Path.Combine(migrationsPath, "Functions");
            if (!Directory.Exists(path)) return;

            ValidateAllowedFiles(path, StructureRules.FunctionsViewsAllowedFiles, "Migrations/Functions/");
            ValidateTwoCharSubfolders(path, "Migrations/Functions/");
        }

        private void ValidateViews(string migrationsPath)
        {
            var path = Path.Combine(migrationsPath, "Views");
            if (!Directory.Exists(path)) return;

            ValidateAllowedFiles(path, StructureRules.FunctionsViewsAllowedFiles, "Migrations/Views/");
            ValidateTwoCharSubfolders(path, "Migrations/Views/");
        }

        private void ValidateStoredProcedures(string migrationsPath)
        {
            var path = Path.Combine(migrationsPath, "StoredProcedures");
            if (!Directory.Exists(path)) return;

            ValidateNoFiles(path, "Migrations/StoredProcedures/");
            ValidateTwoCharSubfolders(path, "Migrations/StoredProcedures/");
        }

        private void ValidateTables(string migrationsPath)
        {
            var tablesPath = Path.Combine(migrationsPath, "Tables");
            if (!Directory.Exists(tablesPath)) return;

            ValidateNoFiles(tablesPath, "Migrations/Tables/");
            ValidateAllowedFolders(tablesPath, StructureRules.TablesAllowedFolders, "Migrations/Tables/");

            // Tables/Data
            var dataPath = Path.Combine(tablesPath, "Data");
            if (Directory.Exists(dataPath)) {
                ValidateNoFiles(dataPath, "Migrations/Tables/Data/");
                ValidateAllowedFolders(dataPath, StructureRules.TablesDataAllowedFolders, "Migrations/Tables/Data/");

                // Tables/Data/Md
                var mdPath = Path.Combine(dataPath, "Md");
                if (Directory.Exists(mdPath)) {
                    ValidateExactFiles(mdPath, StructureRules.TablesMdAllowedFiles, "Migrations/Tables/Data/Md/");
                    ValidateNoFolders(mdPath, "Migrations/Tables/Data/Md/");
                }
            }

            // Tables/Releases
            var releasesPath = Path.Combine(tablesPath, "Releases");
            if (Directory.Exists(releasesPath)) {
                ValidateAllowedFiles(releasesPath, StructureRules.TablesReleasesAllowedFiles, "Migrations/Tables/Releases/");
                // Validate version folders (e.g., 3.5x, 3.6x) - no files allowed directly
                ValidateReleasesVersionFolders(releasesPath);
            }

            // Tables/Settings
            var settingsPath = Path.Combine(tablesPath, "Settings");
            if (Directory.Exists(settingsPath)) {
                ValidateNoFiles(settingsPath, "Migrations/Tables/Settings/");
                ValidateTwoCharSubfolders(settingsPath, "Migrations/Tables/Settings/");
            }
        }

        private void ValidateAllowedFiles(string path, string[] allowedFiles, string location)
        {
            var files = Directory.GetFiles(path).Select(Path.GetFileName).ToList();
            foreach (var file in files) {
                if (!allowedFiles.Contains(file, StringComparer.OrdinalIgnoreCase)) {
                    _errors.Add($"{location}: Unexpected file '{file}'. Allowed: {string.Join(", ", allowedFiles)}");
                }
            }
        }

        private void ValidateExactFiles(string path, string[] expectedFiles, string location)
        {
            var files = Directory.GetFiles(path).Select(Path.GetFileName).ToList();

            // Check for unexpected files
            foreach (var file in files) {
                if (!expectedFiles.Contains(file, StringComparer.OrdinalIgnoreCase)) {
                    _errors.Add($"{location}: Unexpected file '{file}'.");
                }
            }

            // Check for missing files
            foreach (var expected in expectedFiles) {
                if (!files.Contains(expected, StringComparer.OrdinalIgnoreCase)) {
                    _errors.Add($"{location}: Missing required file '{expected}'.");
                }
            }
        }

        private void ValidateAllowedFolders(string path, string[] allowedFolders, string location)
        {
            var folders = Directory.GetDirectories(path).Select(Path.GetFileName).ToList();
            foreach (var folder in folders) {
                if (!allowedFolders.Contains(folder, StringComparer.OrdinalIgnoreCase)) {
                    _errors.Add($"{location}: Unexpected folder '{folder}'. Allowed: {string.Join(", ", allowedFolders)}");
                }
            }
        }

        private void ValidateNoFiles(string path, string location)
        {
            var files = Directory.GetFiles(path).Select(Path.GetFileName).ToList();
            foreach (var file in files) {
                _errors.Add($"{location}: Unexpected file '{file}'. No files allowed at this level.");
            }
        }

        private void ValidateNoFolders(string path, string location)
        {
            var folders = Directory.GetDirectories(path).Select(Path.GetFileName).ToList();
            foreach (var folder in folders) {
                _errors.Add($"{location}: Unexpected folder '{folder}'. No folders allowed at this level.");
            }
        }

        private void ValidateTwoCharSubfolders(string path, string location)
        {
            var folders = Directory.GetDirectories(path).Select(Path.GetFileName).ToList();
            foreach (var folder in folders) {
                if (folder == null || !TwoCharFolderPattern().IsMatch(folder)) {
                    _errors.Add($"{location}: Folder '{folder}' must be exactly 2 characters (e.g., 'Ac', 'Db').");
                }
            }
        }

        private void ValidateReleasesVersionFolders(string releasesPath)
        {
            var versionFolders = Directory.GetDirectories(releasesPath);
            foreach (var versionFolder in versionFolders) {
                var folderName = Path.GetFileName(versionFolder);
                ValidateNoFiles(versionFolder, $"Migrations/Tables/Releases/{folderName}/");
            }
        }
    }
}
