// -----------------------------------------------------------------------------
// <copyright company="Hypothekarbank Lenzburg">
//     Copyright (c) Hypothekarbank Lenzburg. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;
using Finstar.DatabaseMigrationGenerator.Application.Output;

namespace Finstar.DatabaseMigrationGenerator.Application.Structure
{
    public partial class StructureValidationService(IConsoleOutput console) : IStructureValidationService
    {
        private readonly List<string> _errors = [];

        [GeneratedRegex(@"^[A-Z][a-z]$", RegexOptions.Compiled)]
        private static partial Regex TwoCharFolderPattern();

        public void Validate(string migrationsPath)
        {
            _errors.Clear();
            console.Write("Validating structure...");

            ValidateAllFolders(migrationsPath);

            if (_errors.Count > 0)
            {
                ReportErrors();
                throw new ValidationException($"Structure validation failed with {_errors.Count} error(s).");
            }

            console.WriteLine(" done");
            console.WriteSuccess("Folder structure validated successfully!");
        }

        private void ValidateAllFolders(string migrationsPath)
        {
            ValidateRootFolder(migrationsPath);
            ValidateAutoGenerated(migrationsPath);
            ValidateFunctionsOrViews(migrationsPath, "Functions");
            ValidateFunctionsOrViews(migrationsPath, "Views");
            ValidateStoredProcedures(migrationsPath);
            ValidateTables(migrationsPath);
        }

        private void ReportErrors()
        {
            console.WriteLine();
            console.WriteLine();
            console.WriteLine("Structure validation errors found:");
            console.WriteLine();
            foreach (var error in _errors)
            {
                console.WriteError($"    - {error}");
            }
            console.WriteLine();
        }

        private void ValidateRootFolder(string path)
        {
            ValidateItems(path, "Migrations/", ItemType.Files, ValidationMode.AllowedOnly, StructureRules.RootAllowedFiles);
            ValidateItems(path, "Migrations/", ItemType.Folders, ValidationMode.AllowedOnly, StructureRules.RootAllowedFolders);
        }

        private void ValidateAutoGenerated(string migrationsPath)
        {
            var path = Path.Combine(migrationsPath, "AutoGenerated");
            if (!Directory.Exists(path)) return;

            ValidateItems(path, "Migrations/AutoGenerated/", ItemType.Files, ValidationMode.None);
            ValidateItems(path, "Migrations/AutoGenerated/", ItemType.Folders, ValidationMode.AllowedOnly, StructureRules.AutoGeneratedAllowedFolders);

            ValidateLeafFolder(Path.Combine(path, "Baseline"), "Migrations/AutoGenerated/Baseline/", StructureRules.BaselineAllowedFiles);
            ValidateLeafFolder(Path.Combine(path, "ChangesetGenerator"), "Migrations/AutoGenerated/ChangesetGenerator/", StructureRules.ChangesetGeneratorAllowedFiles);
        }

        private void ValidateFunctionsOrViews(string migrationsPath, string folderName)
        {
            var path = Path.Combine(migrationsPath, folderName);
            if (!Directory.Exists(path)) return;

            ValidateItems(path, $"Migrations/{folderName}/", ItemType.Files, ValidationMode.AllowedOnly, StructureRules.FunctionsViewsAllowedFiles);
            ValidateTwoCharSubfolders(path, $"Migrations/{folderName}/");

            var changeLogValidator = new ChangeLogValidator(_errors);
            changeLogValidator.ValidateSchemaChangeLog(path, folderName);
        }

        private void ValidateStoredProcedures(string migrationsPath)
        {
            var path = Path.Combine(migrationsPath, "StoredProcedures");
            if (!Directory.Exists(path)) return;

            ValidateItems(path, "Migrations/StoredProcedures/", ItemType.Files, ValidationMode.None);
            ValidateTwoCharSubfolders(path, "Migrations/StoredProcedures/");
        }

        private void ValidateTables(string migrationsPath)
        {
            var tablesPath = Path.Combine(migrationsPath, "Tables");
            if (!Directory.Exists(tablesPath)) return;

            ValidateItems(tablesPath, "Migrations/Tables/", ItemType.Files, ValidationMode.None);
            ValidateItems(tablesPath, "Migrations/Tables/", ItemType.Folders, ValidationMode.AllowedOnly, StructureRules.TablesAllowedFolders);

            ValidateTablesData(tablesPath);
            ValidateTablesReleases(tablesPath);
            ValidateTablesSettings(tablesPath);
        }

        private void ValidateTablesData(string tablesPath)
        {
            var dataPath = Path.Combine(tablesPath, "Data");
            if (!Directory.Exists(dataPath)) return;

            ValidateItems(dataPath, "Migrations/Tables/Data/", ItemType.Files, ValidationMode.None);
            ValidateItems(dataPath, "Migrations/Tables/Data/", ItemType.Folders, ValidationMode.AllowedOnly, StructureRules.TablesDataAllowedFolders);

            ValidateLeafFolder(Path.Combine(dataPath, "Md"), "Migrations/Tables/Data/Md/", StructureRules.TablesMdAllowedFiles);
        }

        private void ValidateTablesReleases(string tablesPath)
        {
            var releasesPath = Path.Combine(tablesPath, "Releases");
            if (!Directory.Exists(releasesPath)) return;

            ValidateItems(releasesPath, "Migrations/Tables/Releases/", ItemType.Files, ValidationMode.AllowedOnly, StructureRules.TablesReleasesAllowedFiles);

            foreach (var versionFolder in Directory.GetDirectories(releasesPath))
            {
                var folderName = Path.GetFileName(versionFolder);
                ValidateItems(versionFolder, $"Migrations/Tables/Releases/{folderName}/", ItemType.Files, ValidationMode.None);
            }

            var changeLogValidator = new ChangeLogValidator(_errors);
            changeLogValidator.ValidateReleasesChangeLog(releasesPath);
        }

        private void ValidateTablesSettings(string tablesPath)
        {
            var settingsPath = Path.Combine(tablesPath, "Settings");
            if (!Directory.Exists(settingsPath)) return;

            ValidateItems(settingsPath, "Migrations/Tables/Settings/", ItemType.Files, ValidationMode.None);
            ValidateTwoCharSubfolders(settingsPath, "Migrations/Tables/Settings/");
        }

        private void ValidateLeafFolder(string path, string location, string[] expectedFiles)
        {
            if (!Directory.Exists(path)) return;

            ValidateItems(path, location, ItemType.Files, ValidationMode.Exact, expectedFiles);
            ValidateItems(path, location, ItemType.Folders, ValidationMode.None);
        }

        private void ValidateItems(string path, string location, ItemType itemType, ValidationMode mode, string[]? allowedItems = null)
        {
            var items = GetItems(path, itemType);
            var itemTypeName = itemType == ItemType.Files ? "file" : "folder";

            switch (mode)
            {
                case ValidationMode.None:
                    foreach (var item in items)
                    {
                        _errors.Add($"{location}: Unexpected {itemTypeName} '{item}'. No {itemTypeName}s allowed at this level.");
                    }
                    break;

                case ValidationMode.AllowedOnly:
                    foreach (var item in items)
                    {
                        if (!allowedItems!.Contains(item, StringComparer.OrdinalIgnoreCase))
                        {
                            _errors.Add($"{location}: Unexpected {itemTypeName} '{item}'. Allowed: {string.Join(", ", allowedItems!)}");
                        }
                    }
                    break;

                case ValidationMode.Exact:
                    foreach (var item in items)
                    {
                        if (!allowedItems!.Contains(item, StringComparer.OrdinalIgnoreCase))
                        {
                            _errors.Add($"{location}: Unexpected {itemTypeName} '{item}'.");
                        }
                    }
                    foreach (var expected in allowedItems!)
                    {
                        if (!items.Contains(expected, StringComparer.OrdinalIgnoreCase))
                        {
                            _errors.Add($"{location}: Missing required {itemTypeName} '{expected}'.");
                        }
                    }
                    break;
            }
        }

        private static List<string> GetItems(string path, ItemType itemType)
        {
            var items = itemType == ItemType.Files
                ? Directory.GetFiles(path).Select(Path.GetFileName)
                : Directory.GetDirectories(path).Select(Path.GetFileName);

            return items.Where(x => x != null).Cast<string>().ToList();
        }

        private void ValidateTwoCharSubfolders(string path, string location)
        {
            var folders = Directory.GetDirectories(path).Select(Path.GetFileName);
            foreach (var folder in folders)
            {
                if (folder == null || !TwoCharFolderPattern().IsMatch(folder))
                {
                    _errors.Add($"{location}: Folder '{folder}' must be exactly 2 characters (e.g., 'Ac', 'Db').");
                }
            }
        }

        private enum ItemType { Files, Folders }
        private enum ValidationMode { None, AllowedOnly, Exact }
    }
}
