// -----------------------------------------------------------------------------
// <copyright company="Hypothekarbank Lenzburg">
//     Copyright (c) Hypothekarbank Lenzburg. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------------

namespace Finstar.DatabaseMigrationGenerator.Application.Structure
{
    public static class StructureRules
    {
        // Root level
        public static readonly string[] RootAllowedFiles = [
            "HeaderTables.yaml",
            "MasterChangeLog.yaml",
            "liquibase.properties"
        ];

        public static readonly string[] RootAllowedFolders = [
            "AutoGenerated",
            "Bootstrap",
            "Functions",
            "StoredProcedures",
            "Tables",
            "Views"
        ];

        // AutoGenerated
        public static readonly string[] AutoGeneratedAllowedFolders = [
            "Baseline",
            "ChangesetGenerator"
        ];

        // AutoGenerated/Baseline
        public static readonly string[] BaselineAllowedFiles = [
            "ForeignKeys.sql",
            "SchemaChangelog.yaml",
            "Tables.sql",
            "Triggers.sql"
        ];

        // AutoGenerated/ChangesetGenerator
        public static readonly string[] ChangesetGeneratorAllowedFiles = [
            "ChangeLog.yaml",
            "ExtendedPropertiesChangeLog.sql",
            "GrantChangeLog.sql",
            "MdCacheLevelChangeLog.sql",
            "MdDomainTypeChangeLog.sql",
            "MdFieldDataChangeLog.sql",
            "MdGroupAsTextChangeLog.sql",
            "MdGroupChangeLog.sql",
            "MdTableDataDefAsTextChangeLog.sql",
            "MdTableDataDefChangeLog.sql",
            "MdTableTypeChangeLog.sql",
            "MdVisumLevelChangeLog.sql",
            "NavigationIndexChangeLog.sql",
            "StoredProceduresChangeLog.sql",
            "TriggersChangeLog.sql"
        ];

        // Functions, Views (allowed file at root level)
        public static readonly string[] FunctionsViewsAllowedFiles = ["SchemaChangeLog.yaml"];

        // Tables
        public static readonly string[] TablesAllowedFolders = [
            "Data",
            "Releases",
            "Settings"
        ];

        // Tables/Data
        public static readonly string[] TablesDataAllowedFolders = ["Md"];

        // Tables/Data/Md
        public static readonly string[] TablesMdAllowedFiles = [
            "MdCacheLevel.yaml",
            "MdDomainType.yaml",
            "MdGroup.yaml",
            "MdTableType.yaml",
            "MdVisumLevel.yaml"
        ];

        // Tables/Releases
        public static readonly string[] TablesReleasesAllowedFiles = ["ChangeLog.yaml"];
    }
}
